name: .NET Core

on:
  push:
    branches: 
      - dev
      - tech/actions 
      - master
  pull_request:
    branches: 
      - dev

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
    steps:
    

    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101       
    - name: Build with dotnet 
      run: dotnet build --configuration Release 
    - name: publish with dotnet    
      run: dotnet publish --configuration Release
    - name: Upload linux UI Artifact
      if: matrix.os == 'ubuntu-latest' 
      uses: actions/upload-artifact@v2
      with:        
        name: linux-onmov200-UI
        path: /home/runner/work/OnMov200Reader/OnMov200Reader/OnMov200UI/bin/Release/netcoreapp3.0/publish   
    - name: Upload linux CLI Artifact
      if: matrix.os == 'ubuntu-latest' 
      uses: actions/upload-artifact@v2
      with:        
        name: linux-onmov200-CLI
        path: /home/runner/work/OnMov200Reader/OnMov200Reader/Program/bin/Release/netcoreapp3.0/publish 
    - name: Upload windows UI Artifact
      if: matrix.os == 'windows-latest' 
      uses: actions/upload-artifact@v2
      with:        
       name: windows-onmov200-UI
       path: D:\a\OnMov200Reader\OnMov200Reader\OnMov200UI\bin\Release\netcoreapp3.0\publish 
    - name: Upload windows CLI Artifact
      if: matrix.os == 'windows-latest' 
      uses: actions/upload-artifact@v2
      with:        
        name: windows-onmov200-CLI
        path: D:\a\OnMov200Reader\OnMov200Reader\Program\bin\Release\netcoreapp3.0\publish

     

