name: .NET Core

on:
  push:
    branches: 
      - dev
      - tech/actions 
      - master
  pull_request:
    branches: 
      - dev

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
    steps:
    

    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Clean artifacts and nugets 
      run: dotnet clean  --configuration Release && dotnet nuget locals all --clear
    - name: Build with dotnet      
      run: dotnet build --configuration Release 
    - name: publish CLI with dotnet  Win10 x64
      if: matrix.os == 'windows-latest'  
      run: dotnet publish Program/Program.csproj --configuration Release -f netcoreapp3.0 -r win10-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true
    - name: publish GUI with dotnet  Win10 x64
      if: matrix.os == 'windows-latest'  
      run: dotnet publish OnMov200UI/OnMov200UI.csproj --configuration Release -f netcoreapp3.0 -r win10-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true
    - name: publish CLI with dotnet  linux x64
      if: matrix.os == 'ubuntu-latest'  
      run: dotnet publish Program/Program.csproj --configuration Release -f netcoreapp3.0 -r linux-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true
    - name: publish GUI with dotnet  linux x64
      if: matrix.os == 'ubuntu-latest'  
      run: dotnet publish OnMov200UI/OnMov200UI.csproj --configuration Release -f netcoreapp3.0 -r linux-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true
    - name: Upload linux UI Artifact
      if: matrix.os == 'ubuntu-latest' 
      uses: actions/upload-artifact@v2
      with:        
        name: linux-onmov200-UI
        path: /home/runner/work/OnMov200Reader/OnMov200Reader/OnMov200UI/bin/Release/netcoreapp3.0/linux-x64/publish   
    - name: Upload linux CLI Artifact
      if: matrix.os == 'ubuntu-latest' 
      uses: actions/upload-artifact@v2
      with:        
        name: linux-onmov200-CLI
        path: /home/runner/work/OnMov200Reader/OnMov200Reader/Program/bin/Release/netcoreapp3.0/linux-x64/publish 
    - name: Upload windows UI Artifact
      if: matrix.os == 'windows-latest' 
      uses: actions/upload-artifact@v2
      with:        
       name: windows-onmov200-UI
       path: D:\a\OnMov200Reader\OnMov200Reader\OnMov200UI\bin\Release\netcoreapp3.0\win10-x64\publish 
    - name: Upload windows CLI Artifact
      if: matrix.os == 'windows-latest' 
      uses: actions/upload-artifact@v2
      with:        
        name: windows-onmov200-CLI
        path: D:\a\OnMov200Reader\OnMov200Reader\Program\bin\Release\netcoreapp3.0\win10-x64\publish

     

